reviews:
  auto_review: true
  target_branches: ["main", "develop"]

path_instructions:
  - path: "**/*.kt"
    instructions: |
      Check for null safety issues and proper coroutine usage.
      Ensure proper error handling in network calls.
  - path: "**/*.java"
    instructions: |
      Check for potential null pointer exceptions.
      Ensure proper resource management.

general_guidelines: |
  Focus on security vulnerabilities, memory leaks, and performance issues.
  Check for proper error handling in Android components.
