package com.reon.music.core.model

val romanticSongs = emptyList<Song>()
val partySongs = emptyList<Song>()
val sadSongs = emptyList<Song>()
val lofiSongs = emptyList<Song>()
val devotionalSongs = emptyList<Song>()
val workoutSongs = emptyList<Song>()
val retroSongs = emptyList<Song>()
val arijitSinghSongs = emptyList<Song>()
val arRahmanSongs = emptyList<Song>()
val shreyaGhoshalSongs = emptyList<Song>()
val sidSriram = emptyList<Song>()
val anirudhSongs = emptyList<Song>()
val badshah = emptyList<Song>()
val honeysingh = emptyList<Song>()
val kanikKapoor = emptyList<Song>()
